- name: change route53
  route53:
    state: present
    zone: testing.com
    record: www.testing.com
    failover: SECONDARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "5d52c028-0700-4c72-8a7e-957f1d81ff67"
